server:
  port: 8080
  servlet:
    context-path: "/api"


spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  config:
    import:
      - 'classpath:application-aws.yml'
  profiles:
    default: local
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  kafka:
    producer:
      bootstrap-servers:
        - k7d208.p.ssafy.io:8992
        - k7d208.p.ssafy.io:8993
        - k7d208.p.ssafy.io:8994
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer


logging:
  level:
    root: info

---
spring:
  config:
    activate:
      on-profile:
        - local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://k7d208.p.ssafy.io:3208/ddokbun
    username: ddokbun
    password: dd123
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update

  redis:
    host: ddokbun.com
    port: 6379

