version: "3.9"

services:
  fastapi:
    container_name: fastapi-compose
    build:
      context: .
      dockerfile: Dockerfile
    # user: root
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload
    ports:
      - 8082:8080
    volumes:
      - ./app:/app
